/**
 * ARPMart Unified Product Catalog
 * Centralized data source for all categories.
 */
const GLOBAL_CATALOG = [
    // --- Electronics ---
    {
        id: "elec-001",
        name: "Noise Headphones",
        category: "electronics",
        price: 29990,
        rating: 4.8,
        image: "https://avstore.in/cdn/shop/articles/WhatsApp_Image_2025-10-27_at_18.26.38_e8d9b59c_57449fb2-66a8-4bd5-9518-13695d01fa02.jpg?v=1762498044&width=2048",
        brand: "Sony",
        description: "Industry-leading noise cancellation with premium sound quality.",
        inStock: true,
        discount: 10,
        featured: true
    },
    {
        id: "elec-002",
        name: "Apple MacBook Air M2",
        category: "electronics",
        price: 114900,
        rating: 4.9,
        image: "https://ivenus.in/wp-content/uploads/2025/01/0-768x768.jpeg",
        brand: "Apple",
        description: "Supercharged by the M2 chip. Redesigned with a stunning 13.6-inch Liquid Retina display.",
        inStock: true,
        discount: 5
    },

    // --- Mobiles & Tablets Products ---
    {
        id: "mobi-101",
        name: "iPhone 15 Pro",
        category: "mobiles",
        price: 119999,
        rating: 4.8,
        image: "https://cdn.mos.cms.futurecdn.net/v2/t:0,l:250,cw:1500,ch:1125,q:80,w:1500/Zf5hq9r687KghFRhXYiDS7.jpg",
        brand: "Apple",
        description: "A17 Pro chip, 48MP camera, titanium design.",
        inStock: true,
        discount: 5,
        featured: true
    },
    {
        id: "mobi-102",
        name: "Samsung Galaxy S24 Ultra",
        category: "mobiles",
        price: 124999,
        rating: 4.7,
        image: "https://www.triveniworld.com/cdn/shop/files/samsung-galaxy-s24-ultra-5g-ai-smartphone-titanium-violet-12gb-256gb-storage-triveni-world-6.jpg?v=1736304715&width=1946",
        brand: "Samsung",
        description: "200MP camera, Snapdragon 8 Gen 3, S Pen included.",
        inStock: true,
        discount: 8,
        featured: true
    },
    {
        id: "mobi-103",
        name: "OnePlus 12",
        category: "mobiles",
        price: 69999,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/71YzJwmRFCL._AC_UF1000,1000_QL80_.jpg",
        brand: "OnePlus",
        description: "100W fast charging, Hasselblad camera.",
        inStock: true,
        discount: 10,
        featured: true
    },
    {
        id: "mobi-104",
        name: "iPad Air (M2)",
        category: "tablets",
        price: 46999,
        rating: 4.9,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTACF6wl11m41OeYZzfnp37vx766wb9Cv6oZw&s",
        brand: "Apple",
        description: "M2 chip, 10.9\" Liquid Retina, Apple Pencil 2 support.",
        inStock: true,
        discount: 6,
        featured: true
    },
    {
        id: "mobi-105",
        name: "Google Pixel 8 Pro",
        category: "mobiles",
        price: 84999,
        rating: 4.7,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=600",
        brand: "Google",
        description: "AI-powered camera, Tensor G3 chip, 7 years updates.",
        inStock: true,
        discount: 12,
        featured: true
    },
    {
        id: "mobi-106",
        name: "Xiaomi 14 Ultra",
        category: "mobiles",
        price: 79999,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/71yquQmo6SL.jpg",
        brand: "Xiaomi",
        description: "Leica quad camera, 120W charging, Snapdragon 8 Gen 3.",
        inStock: true,
        discount: 15,
        featured: false
    },
    {
        id: "mobi-107",
        name: "Realme GT 5 Pro",
        category: "mobiles",
        price: 44999,
        rating: 4.4,
        image: "https://i.gadgets360cdn.com/products/large/realme-gt-5-652x800-1693219308.jpg",
        brand: "Realme",
        description: "144Hz display, 240W charging, premium performance.",
        inStock: true,
        discount: 20,
        featured: false
    },
    {
        id: "mobi-108",
        name: "Samsung Galaxy Tab S9",
        category: "tablets",
        price: 67999,
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600",
        brand: "Samsung",
        description: "11\" AMOLED, S Pen included, DeX mode support.",
        inStock: true,
        discount: 10,
        featured: true
    },
    {
        id: "mobi-109",
        name: "Nothing Phone (2)",
        category: "mobiles",
        price: 44999,
        rating: 4.5,
        image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/315648_0_mtuxnw.png?tr=w-600",
        brand: "Nothing",
        description: "Glyph interface, transparent design, Snapdragon 8+ Gen 1.",
        inStock: true,
        discount: 18,
        featured: false
    },
    {
        id: "mobi-110",
        name: "iPad Pro 12.9\" (M2)",
        category: "tablets",
        price: 106999,
        rating: 4.9,
        image: "https://cdn.renderhub.com/madmix/apple-ipad-pro-12-9-inch-m2/apple-ipad-pro-12-9-inch-m2-12.jpg",
        brand: "Apple",
        description: "Liquid Retina XDR, M2 chip, ProRes video recording.",
        inStock: true,
        discount: 5,
        featured: true
    },
    {
        id: "mobi-111",
        name: "Vivo X100 Pro",
        category: "mobiles",
        price: 64999,
        rating: 4.6,
        image: "https://itradeit.in/edgeassets/uploads/2024/01/product_image_black02.webp",
        brand: "Vivo",
        description: "Zeiss optics, 120W charging, Dimensity 9300.",
        inStock: true,
        discount: 14,
        featured: false
    },
    {
        id: "mobi-112",
        name: "OnePlus Pad",
        category: "tablets",
        price: 37999,
        rating: 4.5,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600",
        brand: "OnePlus",
        description: "11.61\" 144Hz display, 67W charging, ColorOS for Pad.",
        inStock: true,
        discount: 12,
        featured: false
    },
    // --- Fashion ---
    {
        id: "fash-001",
        name: "Classic Beige Trench Coat",
        category: "fashion",
        price: 4999,
        rating: 4.5,
        image: "https://www.only.in/cdn/shop/files/130542101_g0.jpg?v=1745838566&width=2048",
        brand: "Zara",
        description: "Timeless double-breasted trench coat with belt and button details.",
        inStock: true,
        discount: 15,
        featured: true
    },
    {
        id: "fash-002",
        name: "Urban Streetwear Hoodie",
        category: "fashion",
        price: 2499,
        rating: 4.3,
        image: "https://assets.mediamodifier.com/mockups/69205f5d32882e012c6e4894/hoodie-mockup-on-isolated-background-for-urban-streetwear.jpg",
        brand: "H&M",
        description: "Soft cotton-blend hoodie with a relaxed fit.",
        inStock: true,
        discount: 20
    },

    // --- Furniture ---
    {
        id: "furn-001",
        name: "Modern 3-Seater Sofa",
        category: "furniture",
        price: 64999,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/81zNdfxY2YL._AC_UF894,1000_QL80_.jpg",
        brand: "Urban",
        description: "Comfortable 3-seater with removable cushions and solid wood frame.",
        inStock: true,
        discount: 12,
        featured: true
    },
    {
        id: "furn-002",
        name: "Oak Coffee Table",
        category: "furniture",
        price: 18499,
        rating: 4.6,
        image: "https://www.nismaayadecor.in/cdn/shop/files/johnny-solid-oak-wood-rattan-coffee-table_1.jpg?v=1725612161&width=1080",
        brand: "Scandi",
        description: "Solid oak table with matte finish and minimal design.",
        inStock: true,
        discount: 5
    },
    {
        id: "furn-003",
        name: "Ergonomic Office Chair",
        category: "furniture",
        price: 14999,
        rating: 4.5,
        image: "https://image.springbeetle.com/cdn-cgi/image/dpr=1,format=webp/https://s3.springbeetle.eu/dev-de-s3-flexispot/commodity/item/1028_file_Frame%201321317300.jpg",
        brand: "Urban",
        description: "Breathable mesh back with premium lumbar support.",
        inStock: true,
        discount: 10
    },

    // --- TV & Appliances ---
    {
        id: "app-001",
        name: "50\" 4K Smart LED TV",
        category: "appliances",
        price: 39999,
        rating: 4.5,
        image: "https://image.made-in-china.com/202f0j00guUqoRcGRQkW/High-Quality-Television-50-Inch-4K-HD-Smart-TV-Explosion-Proof-Curved-LED-TV-Android-LCD-Flatscreen-TV.webp",
        brand: "ViewMax",
        description: "Crystal clear 4K resolution with HDR10 support.",
        inStock: true,
        discount: 5,
        featured: true
    },
    {
        id: "app-002",
        name: "Panasonic Frost-Free Refrigerator 260L",
        category: "appliances",
        price: 28999,
        rating: 4.3,
        image: "https://store.in.panasonic.com/media/catalog/product/cache/40b589206cef99ab7dca1586fe425968/a/r/artboard-1_109.webp",
        brand: "Panasonic",
        description: "Energy-efficient dual cooling with smart inverter technology.",
        inStock: true,
        discount: 0
    },

    // --- Grocery Products ---

    {
        id: "groc-001",
        name: "Organic Coffee Beans (500g)",
        category: "grocery",
        price: 850,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800",
        brand: "Blue Tokai",
        description: "Single-origin Arabica beans, medium dark roast.",
        inStock: true,
        discount: 5,
        featured: true,
        tags: ['coffee', 'beans', 'organic', 'breakfast', 'beverages']
    },
    {
        id: "groc-002",
        name: "Premium Basmati Rice (5kg)",
        category: "grocery",
        price: 599,
        rating: 4.7,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThxHCHa_ugnjDIPe1jwawixCjlvBnBxV5wQw&s",
        brand: "Daawat",
        description: "Extra long grain rice with rich aroma.",
        inStock: true,
        discount: 0,
        featured: true,
        tags: ['rice', 'basmati', 'staple', 'indian', 'cooking']
    },
    {
        id: "groc-003",
        name: "Organic Honey (500ml)",
        category: "grocery",
        price: 449,
        rating: 4.8,
        image: "https://www.umanac.com/cdn/shop/files/01_02f0c81f-e698-46b5-9ea0-acb8abff5e97_533x.jpg?v=1743249530",
        brand: "Dabur",
        description: "Pure, unprocessed honey from Himalayan flowers.",
        inStock: true,
        discount: 10,
        featured: true,
        tags: ['honey', 'organic', 'natural', 'sweetener', 'healthy']
    },
    {
        id: "groc-004",
        name: "Mixed Dry Fruits Combo (500g)",
        category: "grocery",
        price: 799,
        rating: 4.6,
        image: "https://images.naptol.com/usr/local/csp/staticContent/product_images/horizontal/750x750/Premium-Dry-Fruits-Mix-Combo-Pack-of-4-NS01-1.jpg",
        brand: "Nutraj",
        description: "Almonds, cashews, raisins, and walnuts premium mix.",
        inStock: true,
        discount: 15,
        featured: false,
        tags: ['dryfruits', 'nuts', 'snacks', 'healthy', 'gift']
    },
    {
        id: "groc-005",
        name: "Cold Pressed Coconut Oil (1L)",
        category: "grocery",
        price: 349,
        rating: 4.5,
        image: "https://www.tatasimplybetter.com/cdn/shop/files/coconut_02.jpg?v=1723024647",
        brand: "Parachute",
        description: "100% pure virgin coconut oil, cold extracted.",
        inStock: true,
        discount: 8,
        featured: false,
        tags: ['oil', 'coconut', 'cooking', 'natural', 'kitchen']
    },
    {
        id: "groc-006",
        name: "Organic Green Tea (100 bags)",
        category: "grocery",
        price: 299,
        rating: 4.7,
        image: "https://images-cdn.ubuy.co.in/6991fbcacb32f1bea5051f3d-imozai-organic-green-tea-bags-100-count.jpg",
        brand: "Organic India",
        description: "Antioxidant-rich green tea with natural flavor.",
        inStock: true,
        discount: 12,
        featured: true,
        tags: ['tea', 'green', 'organic', 'beverages', 'healthy']
    },
    {
        id: "groc-007",
        name: "Premium Ghee (1L)",
        category: "grocery",
        price: 649,
        rating: 4.9,
        image: "https://images.meesho.com/images/products/596811316/edeye_512.webp?width=512",
        brand: "Amul",
        description: "Pure cow ghee, traditionally churned for rich taste.",
        inStock: true,
        discount: 5,
        featured: true,
        tags: ['ghee', 'cooking', 'indian', 'traditional', 'dairy']
    },
    {
        id: "groc-008",
        name: "Whole Wheat Flour (10kg)",
        category: "grocery",
        price: 449,
        rating: 4.4,
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?q=80&w=800",
        brand: "Aashirvaad",
        description: "100% whole wheat atta, stone ground for nutrition.",
        inStock: true,
        discount: 0,
        featured: false,
        tags: ['flour', 'atta', 'wheat', 'staple', 'cooking']
    },
    {
        id: "groc-009",
        name: "Organic Turmeric Powder (200g)",
        category: "grocery",
        price: 149,
        rating: 4.6,
        image: "https://organicindia.com/cdn/shop/files/TurmericPowder_100g.png?v=1765866616&width=1946",
        brand: "Everest",
        description: "Pure ground turmeric with high curcumin content.",
        inStock: true,
        discount: 10,
        featured: false,
        tags: ['spices', 'turmeric', 'organic', 'cooking', 'indian']
    },
    {
        id: "groc-010",
        name: "Premium Masala Chai Mix (500g)",
        category: "grocery",
        price: 199,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800",
        brand: "Tata Tea",
        description: "Authentic blend of tea leaves with cardamom & ginger.",
        inStock: true,
        discount: 15,
        featured: true,
        tags: ['tea', 'chai', 'masala', 'beverages', 'indian']
    },
    {
        id: "groc-011",
        name: "Organic Quinoa (500g)",
        category: "grocery",
        price: 399,
        rating: 4.5,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800",
        brand: "24 Mantra",
        description: "Protein-rich superfood, gluten-free and versatile.",
        inStock: true,
        discount: 8,
        featured: false,
        tags: ['quinoa', 'organic', 'healthy', 'protein', 'gluten-free']
    },
    {
        id: "groc-012",
        name: "Premium Saffron Threads (1g)",
        category: "grocery",
        price: 1299,
        rating: 4.9,
        image: "https://img.faballey.com/images/Product/YFD37321/d6.jpg",
        brand: "Kashmiri",
        description: "Hand-picked premium saffron for authentic flavor.",
        inStock: true,
        discount: 0,
        featured: true,
        tags: ['saffron', 'premium', 'spices', 'indian', 'luxury']
    },


    // --- Home & Kitchen Products ---

    {
        id: "home-001",
        name: "Premium Cookware Set (5 pcs)",
        category: "home & kitchen",
        price: 2499,
        rating: 4.6,
        image: "https://www.nuovva.co.uk/cdn/shop/files/lifestyle_5_piece_445813645.jpg?v=1770379051&width=1200",
        brand: "Nuovva",
        description: "Non-stick granite finish cookware with induction base.",
        inStock: true,
        discount: 15,
        featured: true
    },
    {
        id: "home-002",
        name: "Stainless Steel Knife Set (6 pcs)",
        category: "home & kitchen",
        price: 1899,
        rating: 4.7,
        image: "https://bergnerhome.in/cdn/shop/files/BG-39213-MM-3.jpg?v=1724246191&width=1500",
        brand: "Bergner",
        description: "High-carbon steel knives with ergonomic handles.",
        inStock: true,
        discount: 20
    },
    {
        id: "home-003",
        name: "Glass Food Storage Containers",
        category: "home & kitchen",
        price: 1299,
        rating: 4.5,
        image: "https://homeessentials.in/cdn/shop/files/m-1_e8094254-ddd6-45b0-b151-dcfa29eb8de7_345x345_crop_center.jpg?v=1757319001",
        brand: "Borosil",
        description: "BPA-free, microwave & dishwasher safe containers.",
        inStock: true,
        discount: 10
    },
    {
        id: "home-004",
        name: "Electric Kettle 1.8L",
        category: "home & kitchen",
        price: 899,
        rating: 4.4,
        image: "https://www.rasoishop.com/cdn/shop/files/8901309227735-6.jpg?v=1701447070&width=1445",
        brand: "Prestige",
        description: "Auto shut-off, boil-dry protection, fast boiling.",
        inStock: true,
        discount: 25
    },
    {
        id: "home-005",
        name: "Cotton Table Cloth Set",
        category: "home & kitchen",
        price: 799,
        rating: 4.3,
        image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/0503ac89-33e1-4ebd-a7ec-b20a286fa848.__CR0,0,970,600_PT0_SX970_V1___.png",
        brand: "HomeCentre",
        description: "Premium cotton, stain-resistant, machine washable.",
        inStock: true,
        discount: 30
    },
    {
        id: "home-006",
        name: "Non-Stick Tawa 28cm",
        category: "home & kitchen",
        price: 649,
        rating: 4.5,
        image: "https://media.landmarkshops.in/cdn-cgi/image/h=550,w=550,q=85,fit=cover/homecentre/1000014347505-1000014347504_01-2100.jpg",
        brand: "Hawkins",
        description: "Induction compatible, even heat distribution.",
        inStock: true,
        discount: 15
    },
    {
        id: "home-007",
        name: "Kitchen Organizer Rack (3 Tier)",
        category: "home & kitchen",
        price: 1199,
        rating: 4.6,
        image: "https://rukminim2.flixcart.com/image/480/480/xif0q/kitchen-rack/9/s/6/stainless-steel-3-tier-multipurpose-storage-organizer-corner-original-imahfyqg3pxu7uqv.jpeg?q=90",
        brand: "IKEA",
        description: "Space-saving stainless steel storage rack.",
        inStock: true,
        discount: 20
    },
    {
        id: "home-008",
        name: "Ceramic Dinner Plate Set (12 pcs)",
        category: "home & kitchen",
        price: 1999,
        rating: 4.7,
        image: "https://market99.com/cdn/shop/files/WW10006828-6_2048x.jpg?v=1750134769",
        brand: "La Opala",
        description: "Microwave safe, scratch-resistant, elegant design.",
        inStock: true,
        discount: 35
    },
    {
        id: "home-009",
        name: "Silicone Spatula Set (5 pcs)",
        category: "home & kitchen",
        price: 499,
        rating: 4.4,
        image: "https://agarolifestyle.com/cdn/shop/files/Slide03_a14dd078-e66e-4634-9dea-43ae917805fe.jpg?v=1758224816",
        brand: "Tupperware",
        description: "Heat-resistant, non-stick friendly, BPA-free.",
        inStock: true,
        discount: 10
    },
    {
        id: "home-010",
        name: "Pressure Cooker 5L",
        category: "home & kitchen",
        price: 2199,
        rating: 4.8,
        image: "https://rukminim2.flixcart.com/image/480/640/xif0q/pressure-cooker/g/n/u/-original-imahggzxhhp82tcs.jpeg?q=90",
        brand: "Prestige",
        description: "Induction base, safety lock, recipe book included.",
        inStock: true,
        discount: 25
    },
    {
        id: "home-011",
        name: "Kitchen Weighing Scale Digital",
        category: "home & kitchen",
        price: 599,
        rating: 4.5,
        image: "https://longwayindia.com/cdn/shop/files/4_2af75784-73e5-4df3-b4e1-961e4e2a7d01.jpg?v=1756816412&width=2400",
        brand: "Accuweight",
        description: "Precision measurement, LCD display, auto-off.",
        inStock: true,
        discount: 15
    },
    {
        id: "home-012",
        name: "Mixing Bowl Set (6 pcs)",
        category: "home & kitchen",
        price: 899,
        rating: 4.6,
        image: "https://acmoria.com/cdn/shop/files/LM-N2609-5_900x_6e8e6ca0-8ee8-4392-9647-bbb75c346fd1.webp?v=1716886820&width=1445",
        brand: "Cello",
        description: "Stainless steel, nested design, dishwasher safe.",
        inStock: true,
        discount: 20
    },

    // --- Travel & Gear ---
    {
        id: "travel-001",
        name: "Hardside Spinner Suitcase",
        category: "travel",
        price: 8499,
        rating: 4.8,
        brand: "SwissGear",
        image: "https://m.media-amazon.com/images/I/614AONRWjBL._AC_UL480_FMwebp_QL65_.jpg",
        description: "Durable hardshell, 360-degree wheels, TSA lock. Ultimate protection for your long voyages.",
        inStock: true,
        discount: 15,
        featured: true
    },
    {
        id: "travel-003",
        name: "Memory Foam Neck Pillow",
        category: "travel",
        price: 2499,
        rating: 4.6,
        brand: "CloudNine",
        image: "https://www.chiroshopping.com.au/wp-content/uploads/2020/10/Memory-Foam-Travel-Neck-Pillow-scaled.webp",
        description: "Ergonomic support, washable cover, compact design. Perfect for long-haul flights.",
        inStock: true,
        discount: 10
    },
    {
        id: "travel-005",
        name: "TSA Toiletry Bag Set",
        category: "travel",
        price: 1499,
        rating: 4.5,
        brand: "ClearWay",
        image: "https://www.ezpacking.com/cdn/shop/products/AmazonListin-ExtraSmallCubes2_2048x.jpg?v=1645647185",
        description: "Leak-proof, transparent compartments, 100ml bottles included. Security compliant.",
        inStock: true,
        discount: 5
    },
    {
        id: "travel-006",
        name: "Compression Packing Cubes",
        category: "travel",
        price: 1799,
        rating: 4.7,
        brand: "PackRight",
        image: "https://m.media-amazon.com/images/I/71ZyDUH6TsL._AC_UY1100_.jpg",
        description: "Set of 6, saves 50% space, durable zippers. Maximize your carry-on capacity.",
        inStock: true,
        discount: 20
    },
    {
        id: "travel-007",
        name: "Portable Power Bank 20000mAh",
        category: "travel",
        price: 2999,
        rating: 4.8,
        brand: "Anker",
        image: "https://5.imimg.com/data5/ECOM/Default/2024/7/433541140/ZC/NA/NY/146821774/ultra-slim-power-bank-20000mah-with-led-digital-display-travel-phone-powerbank-portable-fast-charger-500x500.webp",
        description: "Flight-safe capacity, fast charging, dual USB. Keep devices powered mid-flight.",
        inStock: true,
        discount: 12
    },
    {
        id: "travel-008",
        name: "RFID Passport Holder",
        category: "travel",
        price: 899,
        rating: 4.6,
        brand: "SafeJourney",
        image: "https://images-static.nykaa.com/media/catalog/product/1/f/1f2a56bTAN-800027_1.jpg?tr=w-500",
        description: "Blocks identity theft, holds passport + cards, premium leather. Travel securely.",
        inStock: true,
        discount: 8
    },
    {
        id: "travel-009",
        name: "Travel Eye Mask & Earplugs",
        category: "travel",
        price: 699,
        rating: 4.4,
        brand: "DeepSleep",
        image: "https://changiairport.scene7.com/is/image/changiairport/mp00101604-1-travel-blue-1681620584328-travel-blue--travel-eye-mask-and-ear-plugs-comfort-set?$2x$",
        description: "100% blackout, memory foam, noise reduction. Sleep peacefully on any flight.",
        inStock: true,
        discount: 0
    },

    // Gym
    {
        id: "gym-1",
        name: "Pro Series Adjustable Dumbbells 24kg",
        category: "gym",
        price: 18999,
        rating: 4.8,
        image: "https://www.maxprofitness.in/cdn/shop/files/maxpro-maxbell-24kg-adjustable-dumbbell-15-in-1-compact-home-weight-training-system-8099007_2048x.jpg?v=1769107305",
        brand: "FitMax",
        description: "Space-saving adjustable dumbbells with quick-select dial.",
        inStock: true,
        discount: 15
    },
    {
        id: "gym-2",
        name: "Whey Protein Isolate - 2kg",
        category: "gym",
        price: 6499,
        rating: 4.6,
        image: "https://nutralabz.in/cdn/shop/files/ISOLATE_WHEY_2KG_3.jpg?v=1726754653&width=1080",
        brand: "Optimum Nutrition",
        description: "High-quality protein powder for muscle recovery.",
        inStock: true,
        discount: 0
    },
    {
        id: "gym-3",
        name: "Premium Yoga Mat 8mm",
        category: "gym",
        price: 1299,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=600",
        brand: "Lotus",
        description: "Non-slip eco-friendly yoga mat with alignment lines.",
        inStock: true,
        discount: 10
    },
    {
        id: "gym-4",
        name: "Power Rack with Cable Crossover",
        category: "gym",
        price: 45999,
        rating: 4.7,
        image: "https://images-cdn.ubuy.co.in/66cc4f1dcfddc415be12c711-wall-mounted-squat-rack-sl100-hevay.jpg",
        brand: "IronGrip",
        description: "Commercial grade power rack for serious home gyms.",
        inStock: true,
        discount: 5
    },
    {
        id: "gym-5",
        name: "Pre-Workout Energy Formula",
        category: "gym",
        price: 2499,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/712NpBbcfrL.jpg",
        brand: "Cellucor",
        description: "Explosive energy and laser focus for intense training.",
        inStock: true,
        discount: 0
    },
    {
        id: "gym-6",
        name: "Men's Performance Compression T-Shirt",
        category: "gym",
        price: 1899,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/61AKEOxPusL._AC_UY1100_.jpg",
        brand: "Under Armour",
        description: "Breathable moisture-wicking fabric for intense workouts. Available in Men's and Women's sizes.",
        inStock: true,
        discount: 20
    },
    {
        id: "gym-7",
        name: "Adjustable Weight Bench",
        category: "gym",
        price: 8999,
        rating: 4.6,
        image: "https://images-cdn.ubuy.co.in/65b12c23f7c61a2eb149b820-weight-bench-heavy-duty-adjustable.jpg",
        brand: "FitMax",
        description: "Multi-position bench for incline, decline, and flat exercises.",
        inStock: true,
        discount: 0
    },
    {
        id: "gym-8",
        name: "Resistance Bands Set of 5",
        category: "gym",
        price: 1499,
        rating: 4.7,
        image: "https://www.jiomart.com/images/product/original/rvwpo8sw2a/whinsy-resistance-bands-set-11-pcs-set-of-exercise-bands-include-5-different-levels-exercise-bands-door-anchor-foam-handles-and-carrying-bag-for-workout-resistance-tube-product-images-orvwpo8sw2a-p604024599-4-202308221951.jpg?im=Resize=(420,420)",
        brand: "GripPro",
        description: "Heavy-duty workout bands ranging from 10lbs to 50lbs.",
        inStock: true,
        discount: 10
    },

    // Healthcare
    {
        id: "hc-1",
        name: "Digital Blood Pressure Monitor",
        category: "healthcare",
        price: 2499,
        rating: 4.7,
        image: "https://www.medtechlife.com/blood-pressure-monitors/images/big/BP-18-img-1.jpg",
        brand: "Omron",
        description: "Accurate at-home blood pressure monitoring system.",
        inStock: true,
        discount: 10
    },
    {
        id: "hc-2",
        name: "Premium First Aid Kit Setup",
        category: "healthcare",
        price: 1299,
        rating: 4.9,
        image: "https://cdn01.pharmeasy.in/dam/products_otc/G82941/all-in-one-first-aid-kit-max-6.2-1641794939.jpg",
        brand: "Johnson & Johnson",
        description: "Comprehensive emergency medical kit for home or travel.",
        inStock: true,
        discount: 0
    },
    {
        id: "hc-3",
        name: "Digital Thermometer",
        category: "healthcare",
        price: 399,
        rating: 4.6,
        image: "https://trigofit.in/wp-content/uploads/2025/07/Digital-ai.jpg",
        brand: "Dr Trust",
        description: "Fast and accurate body temperature measurement.",
        inStock: true,
        discount: 5
    },

    {
        id: "hc-4",
        name: "Pulse Oximeter Finger Monitor",
        category: "healthcare",
        price: 1199,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/61hU6hNMuPL._AC_UF1000,1000_QL80_.jpg",
        brand: "AccuSure",
        description: "Measures oxygen saturation and pulse rate instantly.",
        inStock: true,
        discount: 12
    },

    {
        id: "hc-5",
        name: "Infrared Forehead Thermometer",
        category: "healthcare",
        price: 1899,
        rating: 4.5,
        image: "https://images-cdn.ubuy.co.in/636b42853f400e52cb757772-infrared-forehead-thermometer.jpg",
        brand: "BPL Medical",
        description: "Contactless infrared thermometer for quick temperature checks.",
        inStock: true,
        discount: 8
    },

    {
        id: "hc-6",
        name: "Hand Sanitizer Pack (500ml)",
        category: "healthcare",
        price: 249,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?q=80&w=600",
        brand: "Dettol",
        description: "Alcohol-based sanitizer that kills 99.9% of germs.",
        inStock: true,
        discount: 5
    },

    {
        id: "hc-7",
        name: "Disposable Face Mask (Pack of 50)",
        category: "healthcare",
        price: 349,
        rating: 4.6,
        image: "https://5.imimg.com/data5/SELLER/Default/2021/7/UC/TA/PF/78372204/surgical-mask-pack-of-50.jpg",
        brand: "3M",
        description: "Protective 3-layer masks for daily hygiene and safety.",
        inStock: true,
        discount: 15
    },

    {
        id: "hc-8",
        name: "Orthopedic Knee Support Brace",
        category: "healthcare",
        price: 799,
        rating: 4.5,
        image: "https://s7e5a.scene7.com/is/image/medi/Collamed-CA-LVR-GenV-9243?$Product-medical-2to3$&wid=420&hei=630",
        brand: "Vissco",
        description: "Provides stability and support for knee joints during activity.",
        inStock: true,
        discount: 10
    },

    {
        id: "hc-9",
        name: "Hot Water Heating Pad",
        category: "healthcare",
        price: 499,
        rating: 4.7,
        image: "https://www.jiomart.com/images/product/original/rvzgsaisog/ecommercehub-hot-water-bag-for-pain-relief-warm-bag-non-electric-heating-pad-massager-for-heat-therapy-and-instant-relief-from-body-stomach-joint-knee-back-pain-incomplete-product-images-orvzgsaisog-p610077859-0-202410071237.jpg?im=Resize=(420,420)",
        brand: "Dr Ortho",
        description: "Electric heating pad for pain relief and muscle relaxation.",
        inStock: true,
        discount: 6
    },
    {
        id: "hc-10",
        name: "Vitamin C Tablets (Immunity Booster)",
        category: "healthcare",
        price: 699,
        rating: 4.8,
        image: "https://assets.myntassets.com/assets/images/2025/NOVEMBER/29/iihKKQv4_c9f25a7cc436404e8d159353e0de113e.jpg",
        brand: "HealthKart",
        description: "Daily vitamin supplement to support immunity and energy.",
        inStock: true,
        discount: 10
    },
    {
        id: "hc-11",
        name: "Paracetamol 500mg Tablets (Strip of 10)",
        category: "healthcare",
        price: 25,
        rating: 4.9,
        image: "https://5.imimg.com/data5/SELLER/Default/2023/10/351875309/MV/JV/AI/53033581/paracetamol-tablets-ip-500x500.jpg",
        brand: "Dolo",
        description: "Effective pain relief and fever reducer. Trusted by doctors.",
        inStock: true,
        discount: 0,
        featured: true,
        tags: ['medicine', 'tablet', 'fever', 'pain', 'paracetamol', 'dolo']
    },
    {
        id: "hc-12",
        name: "Calpol 650mg Tablets (Strip of 15)",
        category: "healthcare",
        price: 45,
        rating: 4.8,
        image: "https://ik.imagekit.io/wlfr/wellness/images/products/410288-1.jpg",
        brand: "Calpol",
        description: "Fast-acting relief from headache, body pain, and fever.",
        inStock: true,
        discount: 5,
        featured: true,
        tags: ['medicine', 'tablet', 'fever', 'pain', 'calpol', 'headache']
    },
    {
        id: "hc-13",
        name: "Paracetamol Suspension Syrup (60ml)",
        category: "healthcare",
        price: 65,
        rating: 4.7,
        image: "https://mediboonpharma.com/wp-content/uploads/2020/12/paracetamol-Pediatrics-oral-suspension-ip.png",
        brand: "Pyrigesic",
        description: "Liquid syrup for children, relieves fever and mild pain.",
        inStock: true,
        discount: 0,
        featured: false,
        tags: ['medicine', 'syrup', 'liquid', 'children', 'fever', 'paracetamol']
    },
    {
        id: "hc-14",
        name: "Horsefir Herbal Tablets (Pack of 30)",
        category: "healthcare",
        price: 299,
        rating: 4.5,
        image: "https://www.arayurveda.com/product/0c2a31fe-c4e1-4feb-8a61-13feedb35877.webp",
        brand: "Himalaya",
        description: "Ayurvedic herbal tablets for joint pain and inflammation.",
        inStock: true,
        discount: 10,
        featured: false,
        tags: ['medicine', 'tablet', 'herbal', 'ayurvedic', 'joint', 'pain']
    },
    {
        id: "hc-15",
        name: "Kidney Care Tablets (Pack of 60)",
        category: "healthcare",
        price: 449,
        rating: 4.6,
        image: "https://5.imimg.com/data5/SELLER/Default/2022/8/JX/UG/YN/116728969/kidney-care-tablets.jpg",
        brand: "Himalaya",
        description: "Supports kidney function and urinary tract health naturally.",
        inStock: true,
        discount: 8,
        featured: true,
        tags: ['medicine', 'tablet', 'kidney', 'health', 'ayurvedic', 'supplement']
    },
    {
        id: "hc-16",
        name: "Liver Care Tablets (Pack of 60)",
        category: "healthcare",
        price: 399,
        rating: 4.7,
        image: "https://cdn01.pharmeasy.in/dam/products_otc/A89623/dr-vaidyas-liver-care-60-tablets-2-1738021015.jpg",
        brand: "Himalaya",
        description: "Protects liver from toxins and supports healthy liver function.",
        inStock: true,
        discount: 12,
        featured: true,
        tags: ['medicine', 'tablet', 'liver', 'health', 'ayurvedic', 'detox']
    },
    {
        id: "hc-17",
        name: "Moxifloxacin eye drop",
        category: "healthcare",
        price: 349,
        rating: 4.5,
        image: "https://www.zexuspharma.com/wp-content/uploads/2021/07/zeximox-3.jpg",
        brand: "HealthKart",
        description: "Supports eye health with lutein, zeaxanthin, and vitamins.",
        inStock: true,
        discount: 5,
        featured: false,
        tags: ['medicine', 'tablet', 'eyes', 'vision', 'supplement', 'health']
    },
    {
        id: "hc-18",
        name: "Clotrimazole (Skin Infection Cream)",
        category: "healthcare",
        price: 149,
        rating: 4.6,
        image: "https://microwinlabs.com/wp-content/uploads/2022/01/6.jpg",
        brand: "Candid",
        description: "Antifungal cream for skin infections, itching, and rashes.",
        inStock: true,
        discount: 0,
        featured: false,
        tags: ['medicine', 'cream', 'skin', 'infection', 'antifungal', 'topical']
    },
    {
        id: "hc-19",
        name: "Cold & Cough Syrup (100ml)",
        category: "healthcare",
        price: 89,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71QYmwne2uL.jpg",
        brand: "Benadryl",
        description: "Relieves cough, cold, sore throat, and nasal congestion.",
        inStock: true,
        discount: 10,
        featured: true,
        tags: ['medicine', 'syrup', 'cold', 'cough', 'throat', 'relief']
    },
    {
        id: "hc-20",
        name: "Dry Cough Syrup",
        category: "healthcare",
        price: 95,
        rating: 4.7,
        image: "https://images.apollo247.in/pub/media/catalog/product/a/s/asc0042-.png",
        brand: "Ascoril",
        description: "Effective for dry, irritating cough with soothing action.",
        inStock: true,
        discount: 8,
        featured: false,
        tags: ['medicine', 'syrup', 'cough', 'dry', 'throat', 'relief']
    },
    {
        id: "hc-21",
        name: "Ibuprofen (Headache Relief tablets)",
        category: "healthcare",
        price: 35,
        rating: 4.9,
        image: "https://5.imimg.com/data5/SELLER/Default/2023/7/325863554/WI/JM/SY/135658020/ibuprofen-tablets-ip-200-mg-.jpg",
        brand: "Combiflam",
        description: "Fast relief from tension headaches, migraines, and body pain.",
        inStock: true,
        discount: 0,
        featured: true,
        tags: ['medicine', 'tablet', 'headache', 'migraine', 'pain', 'relief']
    },
    {
        id: "hc-22",
        name: "Multivitamin Tablets",
        category: "healthcare",
        price: 249,
        rating: 4.8,
        image: "https://onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/25b8159b11674e3780b312a041ed5577.jpg?dpr=3&format=auto",
        brand: "Supradyn",
        description: "Daily multivitamin supplement for energy and immunity.",
        inStock: true,
        discount: 15,
        featured: true,
        tags: ['medicine', 'tablet', 'vitamin', 'supplement', 'immunity', 'energy']
    },
    {
        id: "hc-23",
        name: "Calcium + Vitamin D3 Tablets",
        category: "healthcare",
        price: 199,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71+-Qc7Ek7L._AC_UF350,350_QL80_.jpg",
        brand: "Shelcal",
        description: "Supports bone health, muscle function, and calcium absorption.",
        inStock: true,
        discount: 10,
        featured: false,
        tags: ['medicine', 'tablet', 'calcium', 'vitamin', 'bone', 'health']
    },
    {
        id: "hc-24",
        name: "Iron + Folic Acid Tablets",
        category: "healthcare",
        price: 129,
        rating: 4.6,
        image: "https://tiimg.tistatic.com/fp/1/003/301/dexorange-capsules-850.jpg",
        brand: "Dexorange",
        description: "Prevents anemia, supports red blood cell production.",
        inStock: true,
        discount: 5,
        featured: false,
        tags: ['medicine', 'tablet', 'iron', 'folic', 'anemia', 'blood']
    },
    {
        id: "hc-25",
        name: "Probiotic Capsules",
        category: "healthcare",
        price: 299,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71EnTz13ssL.jpg",
        brand: "Enterogermina",
        description: "Restores gut health, aids digestion, boosts immunity.",
        inStock: true,
        discount: 12,
        featured: true,
        tags: ['medicine', 'capsule', 'probiotic', 'gut', 'digestion', 'health']
    },

    // Books
    {
        id: "bk-1",
        name: "The Psychology of Money",
        category: "books",
        price: 499,
        rating: 4.8,
        image: "https://siddharthchatterjee.com/wp-content/uploads/2023/09/psych-money-cover.jpeg",
        brand: "Morgan Housel",
        description: "Timeless lessons on wealth, greed, and happiness.",
        inStock: true,
        discount: 5
    },
    {
        id: "bk-2",
        name: "Premium Leather Notebook",
        category: "books",
        price: 899,
        rating: 4.7,
        image: "https://www.carveon.com/cdn/shop/products/A5_Pen-Tan-Top-Down-0011-featured_7787bdae-d442-4509-8965-d36077e3d647_600x.jpg?v=1671008170",
        brand: "Moleskine",
        description: "Classic ruled notebook with high-quality paper.",
        inStock: true,
        discount: 0
    },
    {
        id: "bk-3",
        name: "Atomic Habits",
        category: "books",
        price: 399,
        rating: 4.9,
        image: "https://cultivatewhatmatters.com/cdn/shop/articles/atomic-habits.jpg?v=1624827508",
        brand: "James Clear",
        description: "An easy & proven way to build good habits & break bad ones.",
        inStock: true,
        discount: 10
    },
    {
        id: "bk-4",
        name: "Engineering Mathematics Textbook",
        category: "books",
        price: 650,
        rating: 4.5,
        image: "https://khannapublishers.in/image/cache/catalog/apr19/Elemantary%20Engineering%20Mathematics-500x500.jpg",
        brand: "B.S. Grewal",
        description: "Comprehensive textbook for higher engineering mathematics.",
        inStock: true,
        discount: 0
    },
    {
        id: "bk-5",
        name: "Premium Pen Set (Pack of 5)",
        category: "books",
        price: 1299,
        rating: 4.6,
        image: "https://rukmini1.flixcart.com/image/1500/1500/xif0q/pen/s/1/o/-original-imah87yzhfj5f3pb.jpeg?q=70",
        brand: "Parker",
        description: "Classic jotter ballpoint pens with stainless steel body.",
        inStock: true,
        discount: 15
    },
    {
        id: "bk-6",
        name: "Sapiens: A Brief History of Humankind",
        category: "books",
        price: 549,
        rating: 4.8,
        image: "https://www.ynharari.com/wp-content/uploads/2017/01/sapiens.png",
        brand: "Yuval Noah Harari",
        description: "Bold, wide-ranging exploration of human history.",
        inStock: true,
        discount: 8
    },
    {
        id: "bk-7",
        name: "A4 Spiral Notebook Pack (3 pcs)",
        category: "books",
        price: 349,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/51JPOHfB--L._AC_UF1000,1000_QL80_.jpg",
        brand: "Classmate",
        description: "200-page ruled spiral notebooks for college and office.",
        inStock: true,
        discount: 0
    },
    {
        id: "bk-8",
        name: "Rich Dad Poor Dad",
        category: "books",
        price: 399,
        rating: 4.7,
        image: "https://gyaanstore.com/cdn/shop/files/240_110f4f1b-4f70-40a6-8bab-343e71b4832f.png?v=1757578339&width=1946",
        brand: "Robert Kiyosaki",
        description: "What the rich teach their kids about money that the poor do not.",
        inStock: true,
        discount: 5
    },

    // Jewelry
    {
        id: "jw-1",
        name: "18K Gold Plated Minimalist Necklace",
        category: "jewelry",
        price: 3499,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1599643478524-fbeb427f587a?q=80&w=600",
        brand: "LuxeGems",
        description: "Elegant thin chain with a small geometric pendant.",
        inStock: true,
        discount: 20
    },
    {
        id: "jw-2",
        name: "Diamond Solitaire Ring 0.5 ct",
        category: "jewelry",
        price: 85999,
        rating: 5.0,
        image: "https://images.unsplash.com/photo-1605100804763-247f66126e28?q=80&w=600",
        brand: "Tiffany & Co.",
        description: "Brilliant cut engagement ring in platinum setting.",
        inStock: true,
        discount: 0
    },
    {
        id: "jw-3",
        name: "Silver Pearl Drop Earrings",
        category: "jewelry",
        price: 1999,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/51a3cSFvURL._AC_UF1000,1000_QL80_.jpg",
        brand: "Swarovski",
        description: "Freshwater pearl earrings with sterling silver hooks.",
        inStock: true,
        discount: 10
    },
    {
        id: "jw-4",
        name: "Titan Analog Watch for Men",
        category: "jewelry",
        price: 4999,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/71h2K2OQSIL._AC_UY1000_.jpg",
        brand: "Titan",
        description: "Classic analog watch with leather strap and date display.",
        inStock: true,
        discount: 12
    },
    {
        id: "jw-5",
        name: "Gold Temple Bangle Set",
        category: "jewelry",
        price: 12999,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71q1X0cPMXL._AC_UY1000_.jpg",
        brand: "Tanishq",
        description: "Traditional south Indian gold-plated temple bangles set of 4.",
        inStock: true,
        discount: 5
    },
    {
        id: "jw-6",
        name: "Rose Gold Charm Bracelet",
        category: "jewelry",
        price: 2499,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/61qg2ao0ycL._AC_UY1000_.jpg",
        brand: "Pandora",
        description: "Rose gold bracelet with customizable charm slots.",
        inStock: true,
        discount: 15
    },
    {
        id: "jw-7",
        name: "Fossil Smartwatch Gen 6",
        category: "jewelry",
        price: 21999,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/71OjVvdjCvL._AC_UY1000_.jpg",
        brand: "Fossil",
        description: "Hybrid smartwatch with heart rate, SpO2, and fitness tracking.",
        inStock: true,
        discount: 18
    },
    {
        id: "jw-8",
        name: "Diamond Studded Nose Pin",
        category: "jewelry",
        price: 5999,
        rating: 4.9,
        image: "https://m.media-amazon.com/images/I/31-5NIw4XML._AC_UY1000_.jpg",
        brand: "Kalyan Jewellers",
        description: "Natural diamond nose pin set in 18K white gold.",
        inStock: true,
        discount: 0
    },

    // Automotive
    {
        id: "am-1",
        name: "Advanced Ceramic Coating Spray",
        category: "automotive",
        price: 1499,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/81VEiXp6tzL._AC_UF1000,1000_QL80_.jpg",
        brand: "Meguiar's",
        description: "Long-lasting protection and ultimate hydrophobic shine.",
        inStock: true,
        discount: 0
    },
    {
        id: "am-2",
        name: "Heavy Duty Air Compressor",
        category: "automotive",
        price: 3299,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71ApRcRI9VL.jpg",
        brand: "Michelin",
        description: "Fast-filling portable tire inflator with digital gauge.",
        inStock: true,
        discount: 10
    },
    {
        id: "am-3",
        name: "Car Dash Cam 4K Ultra HD",
        category: "automotive",
        price: 5999,
        rating: 4.8,
        image: "https://dashcams.co.in/cdn/shop/files/70mai_A810_Dash_Cam_4K.webp?v=1727240916",
        brand: "70mai",
        description: "4K front camera with night vision, parking monitor, and Wi-Fi.",
        inStock: true,
        discount: 15
    },
    {
        id: "am-4",
        name: "Car Seat Cover Set (Complete)",
        category: "automotive",
        price: 2999,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/718APmQFB2L._AC_UF1000,1000_QL80_.jpg",
        brand: "Autofact",
        description: "Premium PU leather seat covers with airbag compatibility.",
        inStock: true,
        discount: 8
    },
    {
        id: "am-5",
        name: "LED Headlight Bulbs H4 (Pair)",
        category: "automotive",
        price: 1899,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/81ZI0ywnfCL._AC_UF1000,1000_QL80_.jpg",
        brand: "Osram",
        description: "12000 lumens ultra-bright LED with plug-and-play installation.",
        inStock: true,
        discount: 10
    },
    {
        id: "am-6",
        name: "Car Vacuum Cleaner Cordless",
        category: "automotive",
        price: 2499,
        rating: 4.6,
        image: "https://rukminim2.flixcart.com/image/480/640/l2f20sw0/vacuum-cleaner/z/g/5/-original-imagdrh7fhsczfsy.jpeg?q=90",
        brand: "Dyson",
        description: "Portable handheld vacuum with strong suction for car interiors.",
        inStock: true,
        discount: 0
    },
    {
        id: "am-7",
        name: "Tyre Pressure Monitoring System",
        category: "automotive",
        price: 3499,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/71a6WCqj+gL._AC_UF1000,1000_QL80_.jpg",
        brand: "TyreMoni",
        description: "Real-time TPMS with solar-powered display and 4 external sensors.",
        inStock: true,
        discount: 12
    },
    {
        id: "am-8",
        name: "Car Phone Holder Magnetic Mount",
        category: "automotive",
        price: 799,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_UF1000,1000_QL80_.jpg",
        brand: "iOttie",
        description: "Strong neodymium magnets with 360° rotation dashboard mount.",
        inStock: true,
        discount: 5
    },

    // Pets
    {
        id: "pt-1",
        name: "Premium Grain-Free Dog Food 15kg",
        category: "pets",
        price: 5499,
        rating: 4.8,
        image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=600",
        brand: "Orijen",
        description: "Biologically appropriate nutrition for all dog breeds.",
        inStock: true,
        discount: 0
    },
    {
        id: "pt-2",
        name: "Interactive Laser Cat Toy",
        category: "pets",
        price: 899,
        rating: 4.5,
        image: "https://images.unsplash.com/photo-1545529468-42764ef8c85f?q=80&w=600",
        brand: "PetSafe",
        description: "Automatic rotating laser prevents pet boredom.",
        inStock: true,
        discount: 15
    },
    {
        id: "pt-3",
        name: "Orthopedic Dog Bed (Large)",
        category: "pets",
        price: 3499,
        rating: 4.9,
        image: "https://m.media-amazon.com/images/I/81YXhdvzOXL._AC_UF1000,1000_QL80_.jpg",
        brand: "FurHaven",
        description: "Memory foam pet bed with removable washable cover.",
        inStock: true,
        discount: 10
    },
    {
        id: "pt-4",
        name: "Cat Scratching Post Tower",
        category: "pets",
        price: 2999,
        rating: 4.6,
        image: "https://m.media-amazon.com/images/I/71OpVOPEpML._AC_UF1000,1000_QL80_.jpg",
        brand: "Trixie",
        description: "Multi-level cat tree with sisal posts and cozy hideaway.",
        inStock: true,
        discount: 5
    },
    {
        id: "pt-5",
        name: "Pet Grooming Kit (7 pcs)",
        category: "pets",
        price: 1499,
        rating: 4.7,
        image: "https://m.media-amazon.com/images/I/71PW-5QSBPL._AC_UF1000,1000_QL80_.jpg",
        brand: "Wahl",
        description: "Professional pet clippers, nail trimmer, comb, and scissors set.",
        inStock: true,
        discount: 12
    },
    {
        id: "pt-6",
        name: "Automatic Pet Water Fountain",
        category: "pets",
        price: 1999,
        rating: 4.8,
        image: "https://m.media-amazon.com/images/I/71QrmYYWKPL._AC_UF1000,1000_QL80_.jpg",
        brand: "Catit",
        description: "Circulating water fountain with triple filtration system.",
        inStock: true,
        discount: 0
    },
    {
        id: "pt-7",
        name: "Reflective Dog Harness (Medium)",
        category: "pets",
        price: 899,
        rating: 4.5,
        image: "https://m.media-amazon.com/images/I/71GR5FHmXLL._AC_UF1000,1000_QL80_.jpg",
        brand: "Ruffwear",
        description: "No-pull harness with reflective straps for safe night walks.",
        inStock: true,
        discount: 8
    },
    {
        id: "pt-8",
        name: "Chew Toy Variety Pack (6 pcs)",
        category: "pets",
        price: 699,
        rating: 4.4,
        image: "https://m.media-amazon.com/images/I/81MndR0mHAL._AC_UF1000,1000_QL80_.jpg",
        brand: "Kong",
        description: "Durable rubber chew toys for aggressive chewers.",
        inStock: true,
        discount: 0
    }

];

// Attach for global access
window.GLOBAL_CATALOG = GLOBAL_CATALOG;
